package com.bll.lnkwrite.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bll.lnkwrite.mvp.model.book.Book;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOOK".
*/
public class BookDao extends AbstractDao<Book, Long> {

    public static final String TABLENAME = "BOOK";

    /**
     * Properties of entity Book.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property BookId = new Property(2, int.class, "bookId", false, "BOOK_ID");
        public final static Property Type = new Property(3, int.class, "type", false, "TYPE");
        public final static Property SubtypeStr = new Property(4, String.class, "subtypeStr", false, "SUBTYPE_STR");
        public final static Property ImageUrl = new Property(5, String.class, "imageUrl", false, "IMAGE_URL");
        public final static Property BookName = new Property(6, String.class, "bookName", false, "BOOK_NAME");
        public final static Property Grade = new Property(7, int.class, "grade", false, "GRADE");
        public final static Property Supply = new Property(8, int.class, "supply", false, "SUPPLY");
        public final static Property DownloadUrl = new Property(9, String.class, "downloadUrl", false, "DOWNLOAD_URL");
        public final static Property BookPath = new Property(10, String.class, "bookPath", false, "BOOK_PATH");
        public final static Property BookDrawPath = new Property(11, String.class, "bookDrawPath", false, "BOOK_DRAW_PATH");
        public final static Property Time = new Property(12, long.class, "time", false, "TIME");
        public final static Property PageIndex = new Property(13, int.class, "pageIndex", false, "PAGE_INDEX");
        public final static Property PageUrl = new Property(14, String.class, "pageUrl", false, "PAGE_URL");
        public final static Property IsLook = new Property(15, boolean.class, "isLook", false, "IS_LOOK");
    }


    public BookDao(DaoConfig config) {
        super(config);
    }
    
    public BookDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOOK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"BOOK_ID\" INTEGER NOT NULL UNIQUE ," + // 2: bookId
                "\"TYPE\" INTEGER NOT NULL ," + // 3: type
                "\"SUBTYPE_STR\" TEXT," + // 4: subtypeStr
                "\"IMAGE_URL\" TEXT," + // 5: imageUrl
                "\"BOOK_NAME\" TEXT," + // 6: bookName
                "\"GRADE\" INTEGER NOT NULL ," + // 7: grade
                "\"SUPPLY\" INTEGER NOT NULL ," + // 8: supply
                "\"DOWNLOAD_URL\" TEXT," + // 9: downloadUrl
                "\"BOOK_PATH\" TEXT," + // 10: bookPath
                "\"BOOK_DRAW_PATH\" TEXT," + // 11: bookDrawPath
                "\"TIME\" INTEGER NOT NULL ," + // 12: time
                "\"PAGE_INDEX\" INTEGER NOT NULL ," + // 13: pageIndex
                "\"PAGE_URL\" TEXT," + // 14: pageUrl
                "\"IS_LOOK\" INTEGER NOT NULL );"); // 15: isLook
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOOK\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Book entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getBookId());
        stmt.bindLong(4, entity.getType());
 
        String subtypeStr = entity.getSubtypeStr();
        if (subtypeStr != null) {
            stmt.bindString(5, subtypeStr);
        }
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(6, imageUrl);
        }
 
        String bookName = entity.getBookName();
        if (bookName != null) {
            stmt.bindString(7, bookName);
        }
        stmt.bindLong(8, entity.getGrade());
        stmt.bindLong(9, entity.getSupply());
 
        String downloadUrl = entity.getDownloadUrl();
        if (downloadUrl != null) {
            stmt.bindString(10, downloadUrl);
        }
 
        String bookPath = entity.getBookPath();
        if (bookPath != null) {
            stmt.bindString(11, bookPath);
        }
 
        String bookDrawPath = entity.getBookDrawPath();
        if (bookDrawPath != null) {
            stmt.bindString(12, bookDrawPath);
        }
        stmt.bindLong(13, entity.getTime());
        stmt.bindLong(14, entity.getPageIndex());
 
        String pageUrl = entity.getPageUrl();
        if (pageUrl != null) {
            stmt.bindString(15, pageUrl);
        }
        stmt.bindLong(16, entity.getIsLook() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Book entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getBookId());
        stmt.bindLong(4, entity.getType());
 
        String subtypeStr = entity.getSubtypeStr();
        if (subtypeStr != null) {
            stmt.bindString(5, subtypeStr);
        }
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(6, imageUrl);
        }
 
        String bookName = entity.getBookName();
        if (bookName != null) {
            stmt.bindString(7, bookName);
        }
        stmt.bindLong(8, entity.getGrade());
        stmt.bindLong(9, entity.getSupply());
 
        String downloadUrl = entity.getDownloadUrl();
        if (downloadUrl != null) {
            stmt.bindString(10, downloadUrl);
        }
 
        String bookPath = entity.getBookPath();
        if (bookPath != null) {
            stmt.bindString(11, bookPath);
        }
 
        String bookDrawPath = entity.getBookDrawPath();
        if (bookDrawPath != null) {
            stmt.bindString(12, bookDrawPath);
        }
        stmt.bindLong(13, entity.getTime());
        stmt.bindLong(14, entity.getPageIndex());
 
        String pageUrl = entity.getPageUrl();
        if (pageUrl != null) {
            stmt.bindString(15, pageUrl);
        }
        stmt.bindLong(16, entity.getIsLook() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Book readEntity(Cursor cursor, int offset) {
        Book entity = new Book( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.getInt(offset + 2), // bookId
            cursor.getInt(offset + 3), // type
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // subtypeStr
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // imageUrl
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // bookName
            cursor.getInt(offset + 7), // grade
            cursor.getInt(offset + 8), // supply
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // downloadUrl
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // bookPath
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // bookDrawPath
            cursor.getLong(offset + 12), // time
            cursor.getInt(offset + 13), // pageIndex
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // pageUrl
            cursor.getShort(offset + 15) != 0 // isLook
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Book entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setBookId(cursor.getInt(offset + 2));
        entity.setType(cursor.getInt(offset + 3));
        entity.setSubtypeStr(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setImageUrl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBookName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setGrade(cursor.getInt(offset + 7));
        entity.setSupply(cursor.getInt(offset + 8));
        entity.setDownloadUrl(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setBookPath(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setBookDrawPath(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setTime(cursor.getLong(offset + 12));
        entity.setPageIndex(cursor.getInt(offset + 13));
        entity.setPageUrl(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setIsLook(cursor.getShort(offset + 15) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Book entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Book entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Book entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
