package com.bll.lnkwrite.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bll.lnkwrite.mvp.model.book.TextbookBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEXTBOOK_BEAN".
*/
public class TextbookBeanDao extends AbstractDao<TextbookBean, Long> {

    public static final String TABLENAME = "TEXTBOOK_BEAN";

    /**
     * Properties of entity TextbookBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property BookId = new Property(2, int.class, "bookId", false, "BOOK_ID");
        public final static Property Category = new Property(3, int.class, "category", false, "CATEGORY");
        public final static Property Type = new Property(4, int.class, "type", false, "TYPE");
        public final static Property ImageUrl = new Property(5, String.class, "imageUrl", false, "IMAGE_URL");
        public final static Property BookName = new Property(6, String.class, "bookName", false, "BOOK_NAME");
        public final static Property Semester = new Property(7, int.class, "semester", false, "SEMESTER");
        public final static Property Area = new Property(8, String.class, "area", false, "AREA");
        public final static Property Grade = new Property(9, int.class, "grade", false, "GRADE");
        public final static Property Subject = new Property(10, int.class, "subject", false, "SUBJECT");
        public final static Property DownloadUrl = new Property(11, String.class, "downloadUrl", false, "DOWNLOAD_URL");
        public final static Property BookPath = new Property(12, String.class, "bookPath", false, "BOOK_PATH");
        public final static Property BookDrawPath = new Property(13, String.class, "bookDrawPath", false, "BOOK_DRAW_PATH");
        public final static Property Time = new Property(14, long.class, "time", false, "TIME");
        public final static Property PageIndex = new Property(15, int.class, "pageIndex", false, "PAGE_INDEX");
        public final static Property PageUrl = new Property(16, String.class, "pageUrl", false, "PAGE_URL");
    }


    public TextbookBeanDao(DaoConfig config) {
        super(config);
    }
    
    public TextbookBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEXTBOOK_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"BOOK_ID\" INTEGER NOT NULL ," + // 2: bookId
                "\"CATEGORY\" INTEGER NOT NULL ," + // 3: category
                "\"TYPE\" INTEGER NOT NULL ," + // 4: type
                "\"IMAGE_URL\" TEXT," + // 5: imageUrl
                "\"BOOK_NAME\" TEXT," + // 6: bookName
                "\"SEMESTER\" INTEGER NOT NULL ," + // 7: semester
                "\"AREA\" TEXT," + // 8: area
                "\"GRADE\" INTEGER NOT NULL ," + // 9: grade
                "\"SUBJECT\" INTEGER NOT NULL ," + // 10: subject
                "\"DOWNLOAD_URL\" TEXT," + // 11: downloadUrl
                "\"BOOK_PATH\" TEXT," + // 12: bookPath
                "\"BOOK_DRAW_PATH\" TEXT," + // 13: bookDrawPath
                "\"TIME\" INTEGER NOT NULL ," + // 14: time
                "\"PAGE_INDEX\" INTEGER NOT NULL ," + // 15: pageIndex
                "\"PAGE_URL\" TEXT);"); // 16: pageUrl
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEXTBOOK_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TextbookBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getBookId());
        stmt.bindLong(4, entity.getCategory());
        stmt.bindLong(5, entity.getType());
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(6, imageUrl);
        }
 
        String bookName = entity.getBookName();
        if (bookName != null) {
            stmt.bindString(7, bookName);
        }
        stmt.bindLong(8, entity.getSemester());
 
        String area = entity.getArea();
        if (area != null) {
            stmt.bindString(9, area);
        }
        stmt.bindLong(10, entity.getGrade());
        stmt.bindLong(11, entity.getSubject());
 
        String downloadUrl = entity.getDownloadUrl();
        if (downloadUrl != null) {
            stmt.bindString(12, downloadUrl);
        }
 
        String bookPath = entity.getBookPath();
        if (bookPath != null) {
            stmt.bindString(13, bookPath);
        }
 
        String bookDrawPath = entity.getBookDrawPath();
        if (bookDrawPath != null) {
            stmt.bindString(14, bookDrawPath);
        }
        stmt.bindLong(15, entity.getTime());
        stmt.bindLong(16, entity.getPageIndex());
 
        String pageUrl = entity.getPageUrl();
        if (pageUrl != null) {
            stmt.bindString(17, pageUrl);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TextbookBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getBookId());
        stmt.bindLong(4, entity.getCategory());
        stmt.bindLong(5, entity.getType());
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(6, imageUrl);
        }
 
        String bookName = entity.getBookName();
        if (bookName != null) {
            stmt.bindString(7, bookName);
        }
        stmt.bindLong(8, entity.getSemester());
 
        String area = entity.getArea();
        if (area != null) {
            stmt.bindString(9, area);
        }
        stmt.bindLong(10, entity.getGrade());
        stmt.bindLong(11, entity.getSubject());
 
        String downloadUrl = entity.getDownloadUrl();
        if (downloadUrl != null) {
            stmt.bindString(12, downloadUrl);
        }
 
        String bookPath = entity.getBookPath();
        if (bookPath != null) {
            stmt.bindString(13, bookPath);
        }
 
        String bookDrawPath = entity.getBookDrawPath();
        if (bookDrawPath != null) {
            stmt.bindString(14, bookDrawPath);
        }
        stmt.bindLong(15, entity.getTime());
        stmt.bindLong(16, entity.getPageIndex());
 
        String pageUrl = entity.getPageUrl();
        if (pageUrl != null) {
            stmt.bindString(17, pageUrl);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TextbookBean readEntity(Cursor cursor, int offset) {
        TextbookBean entity = new TextbookBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.getInt(offset + 2), // bookId
            cursor.getInt(offset + 3), // category
            cursor.getInt(offset + 4), // type
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // imageUrl
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // bookName
            cursor.getInt(offset + 7), // semester
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // area
            cursor.getInt(offset + 9), // grade
            cursor.getInt(offset + 10), // subject
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // downloadUrl
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // bookPath
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // bookDrawPath
            cursor.getLong(offset + 14), // time
            cursor.getInt(offset + 15), // pageIndex
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16) // pageUrl
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TextbookBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setBookId(cursor.getInt(offset + 2));
        entity.setCategory(cursor.getInt(offset + 3));
        entity.setType(cursor.getInt(offset + 4));
        entity.setImageUrl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBookName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSemester(cursor.getInt(offset + 7));
        entity.setArea(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setGrade(cursor.getInt(offset + 9));
        entity.setSubject(cursor.getInt(offset + 10));
        entity.setDownloadUrl(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setBookPath(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setBookDrawPath(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setTime(cursor.getLong(offset + 14));
        entity.setPageIndex(cursor.getInt(offset + 15));
        entity.setPageUrl(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TextbookBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TextbookBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TextbookBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
